function [map ooptim] = invGpac(init, opt, data, hypers, Hrond, ...
                                index, offsets, regOp, objectMean, ...
                                Nalpha, Nbeta, Norder, Nscan, Nbolo, ...
                                Nspeed, uspeed, theSpeeds, varargin)
  %% usage:  inversion ()
  %%
  %%

  ndata = cell(size(data));
  for iscan = 1:Nscan
    ndata(iscan) = {data{iscan} - repmat(offsets, ...
                                         size(data{iscan},1),1)};
  end
  
  [map sortieops histo] = gpac('calcQuadCrit', init, opt, ...
                               'calcQuadGrad', ndata, hypers, Hrond, ...
                               index, regOp, objectMean, Nalpha, ...
                               Nbeta, Norder, Nbolo, Nspeed, Nscan, ...
                               uspeed, theSpeeds, varargin{:});
  
  ooptim = {sortieops histo};
  
end
